services:
     postgres:
        image: bitnami/postgresql:latest
        volumes:
            - ./postgres_data:/var/lib/postgresql/data 
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        ports:
            - "5434:5432"
        networks:
            - dev

volumes:
    postgres_data:
networks:
    dev:
        name: dev
        driver: bridge
